
import type { Metadata } from "next";
import { Inter, Nova_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { createContext } from "vm";
import { useState } from "react";
import KorpaContext from "./context/KorpaContext";
import UserContext from "./context/AuthContext";

const inter = Nova_Mono({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {




  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContext>
          <Navbar />

          <KorpaContext>

            {children}
          </KorpaContext>
        </UserContext>
        <Footer />
      </body>
    </html>
  );
}
